export enum AuditLogActionEnum {
  DELETE_USER = 1,
  CREATE_USER = 2,
  UPDATE_USER = 3,

  CREATE_DEPARTMENT = 4,
  UPDATE_DEPARTMENT = 5,
  ADD_EMPLOYEE_INTO_DEPARTMENT = 6,
  REMOVE_EMPLOYEE_FROM_DEPARTMENT = 7,
  DELETE_DEPARTMENT = 8,
  RESTORE_DEPARTMENT = 9,
  HARD_DELETE_DEPARTMENT = 10,

  UPDATE_ATTENDANCE = 11,
  DELETE_ATTENDANCE = 12,

  UPDATE_USER_DEPARTMENT_PERMISSION = 13,
  UPDATE_USER_PERMISSION = 14,

  UPDATE_COMPANY_LOGO = 15,
  CHANGE_PASSWORD = 16,

  ACCEPT_LEAVE_REQUEST = 17,
  REJECT_LEAVE_REQUEST = 18,
  REMOVE_LEAVE_REQUEST = 19,
  POSTPONE_LEAVE_REQUEST = 20,
  RESTORE_LEAVE_REQUEST = 21,
  DELETE_LEAVE_REQUEST = 22,
  HARD_DELETE_LEAVE_REQUEST = 23,
}
